/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.clsCat;
import Classes.clsDog;
import Classes.clsPet;
import Controller.ctlPet;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class frmPet extends javax.swing.JPanel {
    
    ctlPet ctlPet;
    
    LinkedList<clsDog> DogObjectList = new LinkedList<>();
    LinkedList<clsCat> CatObjectList = new LinkedList<>();

    /**
     * Creates new form frmPet
     */
    public frmPet() {
        initComponents();
        this.ctlPet = new ctlPet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Veterinary = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetObjectList = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodeDog = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNameDog = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBornYearDog = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtColorDog = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbHealthStatusDog = new javax.swing.JComboBox<>();
        txtBreedDog = new javax.swing.JTextField();
        btnCrearDog = new javax.swing.JButton();
        btnBuscarDog = new javax.swing.JButton();
        BtnEditarDog = new javax.swing.JButton();
        btnEliminarDog = new javax.swing.JButton();
        cbPedegree = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Adress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        jButtonAttending = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodeCat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNameCat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbHealthStatusCat = new javax.swing.JComboBox<>();
        txtBornYearCat = new javax.swing.JTextField();
        txtColorCat = new javax.swing.JTextField();
        btnCrearCat = new javax.swing.JButton();
        btnBuscarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        Breed = new javax.swing.JLabel();
        txtBreedCat = new javax.swing.JTextField();
        Doctor = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Licence = new javax.swing.JLabel();
        txtNameDoctor = new javax.swing.JTextField();
        txtLicenceDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setRequestFocusEnabled(false);

        Veterinary.setToolTipText("");

        PetObjectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pe1", "Pet2", "Pet3", "Pet4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(PetObjectList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        Veterinary.addTab("PetList", jPanel1);

        jLabel2.setText("Code");

        txtCodeDog.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel3.setText("Name");

        jLabel4.setText("Born Year");

        jLabel6.setText("Color");

        jLabel5.setText("Healt Status");

        jLabel7.setText("Bredd");

        cbHealthStatusDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo" }));
        cbHealthStatusDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHealthStatusDogActionPerformed(evt);
            }
        });

        btnCrearDog.setText("Crear");
        btnCrearDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDogActionPerformed(evt);
            }
        });

        btnBuscarDog.setText("Buscar");
        btnBuscarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDogActionPerformed(evt);
            }
        });

        BtnEditarDog.setText("Editar");
        BtnEditarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarDogActionPerformed(evt);
            }
        });

        btnEliminarDog.setText("Eliminar");
        btnEliminarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDogActionPerformed(evt);
            }
        });

        cbPedegree.setText("Pedigree ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(btnCrearDog)
                            .addComponent(cbPedegree))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCodeDog, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtBornYearDog))
                            .addComponent(cbHealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtColorDog))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBreedDog))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnBuscarDog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditarDog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarDog)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodeDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtNameDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBornYearDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtColorDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(cbHealthStatusDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBreedDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(cbPedegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDog)
                    .addComponent(btnBuscarDog)
                    .addComponent(BtnEditarDog)
                    .addComponent(btnEliminarDog))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        Veterinary.addTab("DogManager", jPanel5);

        jLabel13.setText("Name");

        Phone.setText("Phone");

        Adress.setText("Adress");

        jButtonAttending.setText("Attending");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(Adress)
                            .addComponent(Phone))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonAttending)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Adress)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonAttending)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Veterinary.addTab("Veterinary", jPanel4);

        jLabel8.setText("Code");

        jLabel9.setText("Name");

        jLabel10.setText("Born Year");

        jLabel11.setText("Color");

        jLabel12.setText("Health Status");

        cbHealthStatusCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saludable", "Enfermo", "" }));

        txtColorCat.setToolTipText("");

        btnCrearCat.setText("Crear");
        btnCrearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCatActionPerformed(evt);
            }
        });

        btnBuscarCat.setText("Buscar");
        btnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatActionPerformed(evt);
            }
        });

        btnEditarCat.setText("Editar");
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });

        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });

        Breed.setText("Breed");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(Breed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBornYearCat, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(txtCodeCat))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtColorCat, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(txtNameCat))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtBreedCat, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbHealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrearCat)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCat)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCat)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodeCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtBornYearCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColorCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbHealthStatusCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Breed)
                    .addComponent(txtBreedCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCat)
                    .addComponent(btnBuscarCat)
                    .addComponent(btnEditarCat)
                    .addComponent(btnEliminarCat))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Veterinary.addTab("CatManager", jPanel3);

        Name.setText("Name");

        Licence.setText("Licence");

        javax.swing.GroupLayout DoctorLayout = new javax.swing.GroupLayout(Doctor);
        Doctor.setLayout(DoctorLayout);
        DoctorLayout.setHorizontalGroup(
            DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Licence)
                    .addComponent(Name))
                .addGap(72, 72, 72)
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenceDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        DoctorLayout.setVerticalGroup(
            DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(txtNameDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Licence)
                    .addComponent(txtLicenceDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        Veterinary.addTab("Doctor", Doctor);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("PetManager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Veterinary)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Veterinary, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarDogActionPerformed
        String code = txtCodeDog.getText();
        for (clsDog dog : DogObjectList) {
            if (dog.getCodigo().equals(code)){
                
                String nombre = txtNameDog.getText();
                String color = txtColorDog.getText();
                int born_year = Integer.parseInt(txtBornYearDog.getText());
                String breed = txtBreedDog.getText();
                String healtstatus = cbHealthStatusDog.getSelectedItem().toString();
                boolean pedigree = cbPedegree.isSelected(); 
                dog.setNombre(nombre);
                dog.setBorn_year(born_year);
                dog.setBreed(breed);
                dog.setPedigree(pedigree);
                dog.setHealtstatus(healtstatus);
                dog.setColor(color);
                this.ClearDogFields();
                this.FillJList();
                JOptionPane.showMessageDialog(this, "record update sucessfuly");
                boolean found = true;
                break;
                
            } else {
                
            }
        }
        boolean found = false;
        
        if (!found){
            JOptionPane.showMessageDialog(this, "CODE NOT FOUND");
        }
    }//GEN-LAST:event_BtnEditarDogActionPerformed

    private void cbHealthStatusDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHealthStatusDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHealthStatusDogActionPerformed

    private void btnCrearDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDogActionPerformed
        // TODO add your handling code here:
        try {
            
            String codigo = txtCodeDog.getText();
        String nombre = txtNameDog.getText();
        String color = txtColorDog.getText();
        String breed = txtBreedDog.getText();
        int born_year = Integer.parseInt (txtBornYearDog.getText());
        String healtstatus = cbHealthStatusDog.getSelectedItem().toString();
        boolean pedigree = cbPedegree.isSelected();  
          
        if (codigo.equals("")|| nombre.equals("") || color.equals("") ){ 
             JOptionPane.showMessageDialog(this, "FILL ALL FIELDS"); 
         
        }else{
            clsDog dog = new clsDog(breed, pedigree, codigo, nombre, born_year, color, healtstatus);
               
            
        DogObjectList.add(dog);
        this.FillJList();
        this.ClearDogFields();
        JOptionPane.showMessageDialog(this, "FILL ALL FIELDS");
            
            }
        
        
        }catch(Exception e) {
        
            JOptionPane.showConfirmDialog(this, "Please add a value ");
            }
    }//GEN-LAST:event_btnCrearDogActionPerformed

    private void btnBuscarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDogActionPerformed
        String code = txtCodeDog.getText();
        clsDog dog = (clsDog) ctlPet.SearchPet(code, "Perro");
        
        if (dog == null){
            JOptionPane.showMessageDialog(this, "Code not found ");
            
        }else{
                txtNameDog.setText(dog.getNombre());
                txtColorDog.setText(dog.getColor());
               
                txtBornYearDog.setText(dog.getborn_year()+ "");
                cbHealthStatusDog.setSelectedItem(dog.getHealtstatus());
                cbPedegree.setSelected(dog.getPedigree());
        }
    }//GEN-LAST:event_btnBuscarDogActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        String code = txtCodeCat.getText();
        boolean found = false;
        for (clsCat cat : CatObjectList) {
            if (cat.getCodigo().equals(code)){
                
                this.DogObjectList.remove(cat);
                this.ClearCatFields();
                this.FillJList();
                JOptionPane.showMessageDialog(this, "record remove sucessfuly");
                found = true;
                break;
                
            } else {
                
            }
        }
        
        if (!found){
            JOptionPane.showMessageDialog(this, "CODE NOT FOUND");
        }
          
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnEliminarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDogActionPerformed
        String code = txtCodeDog.getText();
        boolean found = false;
        for (clsDog dog : DogObjectList) {
            if (dog.getCodigo().equals(code)){
                
                this.DogObjectList.remove(dog);
                this.ClearDogFields();
                this.FillJList();
                JOptionPane.showMessageDialog(this, "record remove sucessfuly");
                found = true;
                break;
            
        }
        
        if (!found){
            JOptionPane.showMessageDialog(this, "CODE NOT FOUND");
        }
    }//GEN-LAST:event_btnEliminarDogActionPerformed
} 
    private void btnCrearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCatActionPerformed
       try {
            
            String codigo = txtCodeCat.getText();
        String nombre = txtNameCat.getText();
        String color = txtColorCat.getText();
        String breed = txtBreedCat.getText();
        int born_year = Integer.parseInt (txtBornYearCat.getText());
        String healtstatus = cbHealthStatusCat.getSelectedItem().toString();
          
          
        if (codigo.equals("")|| nombre.equals("") || color.equals("") ){ 
            JOptionPane.showMessageDialog(this, "FILL ALL FIELDS"); 
         
        }else{
               
           clsCat cat = new clsCat (breed, codigo, nombre, born_year, color, healtstatus);
               
            
        
        
       
            
        CatObjectList.add(cat);
        this.FillJList();
        this.ClearCatFields();
            
            }
        
        
        }catch(Exception e) {
        
            JOptionPane.showConfirmDialog(this, "Please add a value ");
            }
    }//GEN-LAST:event_btnCrearCatActionPerformed

    private void btnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatActionPerformed
        String code = txtCodeCat.getText();
        clsCat cat = (clsCat) ctlPet.SearchPet(code, "Gato");
        
        if (cat == null){
            JOptionPane.showMessageDialog(this, "Code not found ");
            
        }else{
                txtNameCat.setText(cat.getNombre());
                txtColorCat.setText(cat.getColor());
           txtBreedCat.setText(cat.getBreed());
                txtBornYearCat.setText(cat.getborn_year()+ " " );
                cbHealthStatusCat.setSelectedItem(cat.getHealtstatus() + "");
                ;
        }
    }//GEN-LAST:event_btnBuscarCatActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
      String code = txtCodeCat.getText();
        for (clsCat cat : CatObjectList) {
            if (cat.getCodigo().equals(code)){
                
                String nombre = txtNameCat.getText();
                String color = txtColorCat.getText();
                int born_year = Integer.parseInt(txtBornYearCat.getText());
                String breed = txtBreedCat.getText();
                String healtstatus = cbHealthStatusCat.getSelectedItem().toString();
                 
                cat.setNombre(nombre);
                cat.setBorn_year(born_year);
                cat.setBreed(breed);
                 
                cat.setHealtstatus(healtstatus);
                cat.setColor(color);
                this.ClearDogFields();
                this.FillJList();
                JOptionPane.showMessageDialog(this, "record update sucessfuly");
                boolean found = true;
                break;
                
            } else {
                
            }
        }
        boolean found = false;
        
        if (!found){
            JOptionPane.showMessageDialog(this, "CODE NOT FOUND");
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed
       
    
     private void ClearDogFields(){
         txtCodeDog.setText("");
         txtNameDog.setText("");
         txtColorDog.setText("");
         txtBornYearDog.setText("");
         cbHealthStatusDog.setSelectedIndex(0);
         cbPedegree.setSelected(false);
         
     }
      private void ClearCatFields(){
         txtCodeCat.setText("");
         txtNameCat.setText("");
         txtColorCat.setText("");
         txtBornYearCat.setText("");
         cbHealthStatusCat.setSelectedIndex(0);
         }
     private void FillJList(){
         DefaultListModel model = new DefaultListModel();
         int index = 0; 
         
         for (clsDog dog : DogObjectList){
             String data = dog.getNombre() + " - " + dog.getBreed() + " -Perro"; 
             model.add(index, data);
             index++;
                     }
             PetObjectList.setModel(model);
             
     
         
         
         for (clsCat cat : CatObjectList){
             String data = cat.getNombre() + " - " + cat.getBreed() + " -Gato"; 
             model.add(index, data);
             index++;
                     }
             PetObjectList.setModel(model);
             
             
             
             
     }
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run (){
                new frmPet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress;
    private javax.swing.JLabel Breed;
    private javax.swing.JButton BtnEditarDog;
    private javax.swing.JPanel Doctor;
    private javax.swing.JLabel Licence;
    private javax.swing.JLabel Name;
    private javax.swing.JList<String> PetObjectList;
    private javax.swing.JLabel Phone;
    private javax.swing.JTabbedPane Veterinary;
    private javax.swing.JButton btnBuscarCat;
    private javax.swing.JButton btnBuscarDog;
    private javax.swing.JButton btnCrearCat;
    private javax.swing.JButton btnCrearDog;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarDog;
    private javax.swing.JComboBox<String> cbHealthStatusCat;
    private javax.swing.JComboBox<String> cbHealthStatusDog;
    private javax.swing.JCheckBox cbPedegree;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonAttending;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtBornYearCat;
    private javax.swing.JTextField txtBornYearDog;
    private javax.swing.JTextField txtBreedCat;
    private javax.swing.JTextField txtBreedDog;
    private javax.swing.JTextField txtCodeCat;
    private javax.swing.JTextField txtCodeDog;
    private javax.swing.JTextField txtColorCat;
    private javax.swing.JTextField txtColorDog;
    private javax.swing.JTextField txtLicenceDoctor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameCat;
    private javax.swing.JTextField txtNameDoctor;
    private javax.swing.JTextField txtNameDog;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
